before:
  hooks:
    - make clean
    # you may remove this if you don't need go generate
    - go generate ./...
    # Login to dockerhub
    # - echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
    - make login
    # run test
    - make test
builds:
  - main: main.go
    binary: darksky-exporter
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
dist:
  _dist
dockers:
  -
    # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64
    # Templates of the Docker image names.
    image_templates:
    - "billykwooten/darksky-exporter:latest"
    - "billykwooten/darksky-exporter:{{ .Tag }}"
    dockerfile: Dockerfile.gr
    # Skips the docker push. Could be useful if you also do draft releases.
    # Defaults to false.
    skip_push: false
archive:
  format: tar.gz
  files:
    - README.md
    - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
