#!/usr/bin/env bash

set -e -o pipefail +x

cd "$(dirname "$0")"/..

# shellcheck disable=1091
source script/settings

# shellcheck disable=1091
source script/common

if  builtin type -p overalls &>/dev/null; then
    overalls -covermode=atomic -project=github.com/billykwooten/darksky-exporter -- -race -v
    mv overalls.coverprofile darksky-exporter.cover
    go tool cover -func=darksky-exporter.cover
else
    go test -race -v "$(go list ./... | grep -v /vendor/)"
fi

